### PR TITLE
Make response schema validate whole response

### PR DESCRIPTION
**Pull request by acka47**
... and add `type` and `match` as required.
Fixes https://github.com/reconciliation-api/specs/issues/5.

See also https://github.com/reconciliation-api/specs/pull/4#issuecomment-534996592

### CODE REVIEW

**Comment by acka47** [comment]
You are referring to https://github.com/reconciliation-api/specs/blob/ed2fc029efc3d09cfb79110b421078e6ed1ce111/index.html#L257
I am not sure how to update it. What do you think about something like "A reconciliation response is a set of reconciliation candidates for each query string provided"?

**Comment by wetneb** [comment]
Yes! It might need more than a single sentence to be completely clear, using intermediate definitions, but we can tweak that later on.

**Comment by acka47** [comment]
I just chatted with @fsteeg and we agreed upon rather using the term "result" than "response" ("reconciliation result" and "reconciliation result batch") because "response" is regularly used for the server response to a HTTP request. As the spec uses "response" in both meanings it might lead to confusion

https://github.com/reconciliation-api/specs/blob/35c0f1e47d61dfc51af5559f698f3f0c0884c0fb/index.html#L202

What do you think, @wetneb ?
I won'tchange it when used in the context of data extension ("Data Extension Response"), though as the common meaning applies here.

**Comment by acka47** [comment]
With 918d404f7673b4b05543e1118d84c7ecc8e69c8c, I updated the terminology as written in  https://github.com/reconciliation-api/specs/pull/8#issuecomment-535493677, added a defnition for result batch and updated references and descriptions of the schema. Please review, @wetneb .

**Comment by acka47** [comment]
Great, I added myself as editor. Merging.

**Pull request merged**
