### PR TITLE
Add README section on local setup

### PR DESCRIPTION
**Pull request by fsteeg**
Run local web server for data-include support

### CODE REVIEW

**Comment by wetneb** [comment]
Thanks! With my browser (Firefox 68) it seems that `data-include` works even with `file://`, but it might not be true for everyone.

**Comment by fsteeg** [comment]
> With my browser (Firefox 68) it seems that data-include works even with `file://`

Interesting, I also have Firefox 68 (though it also says 'for Linux Mint' in the info screen), and I got ReSpec errors for the data-includes.

**Comment by wetneb** [comment]
Ok. Also I am not sure about this `data-include` business, perhaps it is not that useful to include the source of the JSON Schemas in the specs (linking to them could be enough). I just wanted to play with this nice feature, but it does not mean we should necessarily have it :)

**Comment by fsteeg** [comment]
> perhaps it is not that useful to include the source of the JSON Schemas in the specs (linking to them could be enough)

I like the inclusion because we get syntax coloring and consistent display right in the document, while with links, a JSON plugin would have to be installed in the browser. Inclusion might also be useful for other JSON snippets in the spec (like complex reconciliation requests including properties etc.), which could be edited in separate files, with a nice editor supporting JSON, and sent as data with curl to validate them (even automated).

**Pull request merged**
