### PR TITLE
Add info on rate limit contracts for batches

### PR DESCRIPTION
**Pull request by gitonthescene**
Updated spec as requested in https://github.com/OpenRefine/OpenRefine/issues/3657.  Referred to in #66.

### CODE REVIEW

**Comment by wetneb** [comment]
Thanks! I think this goes in the right direction :)
Here are a few thoughts:
* perhaps these parameters could be grouped into a subobject, to keep the root of the manifest a bit cleaner?
* we would need to add these parameters to some JSON examples and to the JSON schemas for validation (I am not asking that you do this yet, since we should first have an agreement on the desired syntax).

**Comment by gitonthescene** [comment]
Hey there @wetneb, I’m just getting back to this.  I’m not sure I understand what you’re thinking of in terms of a subsection.  Maybe you could offer a concrete suggestion.  Currently, it’s two new parameters that aren’t even necessarily related.

**Comment by wetneb** [comment]
I was thinking that instead of specifying something like
```json
{
    "name": "my recon service",
    "identifierSpace": "my identifier space",
    "schemaSpace": "my schema space",
    "batchSize": 100,
    "batchRate": 10
}
```
we could instead have something like
```json
{
    "name": "my recon service",
    "identifierSpace": "my identifier space",
    "schemaSpace": "my schema space",
    "limits": {
        "batchSize": 100,
        "batchRate": 10
    }
}
```
For me, those parameters are topically related and we might want to introduce more of them in the future, so it feels natural to try to group them together :)

**Comment by gitonthescene** [comment]
I don't mind doing it that way, though I suspect "limits" may be a bit too broad a category to add any cognitive value.  I think rate limiting is likely to come with more parameters eventually that have nothing to do with the batch size.

**Comment by gitonthescene** [comment]
Separately, thinking about how the spec might evolve raises the question about what's the intended process for servers to support a given version of a spec.  I.e. how is the version of the spec being used negotiated between the client and the server.  I see that the server can supply the list of versions it supports in the [service manifest](https://reconciliation-api.github.io/specs/latest/#service-manifest) but it's not clear how the handshake works.

For instance, if we introduced "batchRate" and later changed it to "throttleRate", how would the service manifest indicate which it was offering.  Or if it's able to offer one or the other according to what the client understands, how would it receive the information about what the client is expecting?

For this specific change the server could offer both fields (though that likely means it's not strictly following either spec), but if the meaning of a field changes then even that is not possible.

**Comment by wetneb** [comment]
About the format, my example above was just meant to illustrate what I meant by "subobject": if you can think of a better term to group these two settings, I would be glad to hear it.

About versioning, I suggest we have this discussion somewhere else :)

**Comment by gitonthescene** [comment]
@wetneb I don't know that there is something which applies at this point.  I'm happy with my original suggestion.  Should we just go with that unless you can think up something better?

**Comment by wetneb** [comment]
I think I would still prefer to keep these options grouped, mostly for the sake of not having a plethora of root-level parameters in this JSON object. I think `limits` or `throughput` would both work, but I would be happy with other terms.

Beyond those petty syntax choices I think it would be worth thinking more about the parameters that are actually useful to the services here. In https://github.com/OpenRefine/OpenRefine/issues/3657 you mention the idea of sending all requests in parallel at once and I think that is precisely what many services would really not enjoy. In my experience many services ask clients to cap the number of parallel connections to the service (because open connections are a precious resource for servers).
So instead of / in addition to your `batchRate` I would be tempted to have something like `maxConnections` which would ask a client to cap the number of open sockets to the service.

**Comment by gitonthescene** [comment]
I’m okay with a max connections parameter.  As I said in that issue the server should mostly be responsible for a defensive implementation and shouldn’t rely on clients playing nice.  Also parallelizing a request should allow it to complete quicker and thereby release resources.

But again, I’m mostly interested in batchSize to be able to horizontally scale the requests on the server side.  If the client only sends the current default of ten items at a time, not much can be done by the server to improve the throughput.

**Comment by wetneb** [comment]
Other suggestion of names for this section of the manifest: `serverLimits`.

**Comment by gitonthescene** [comment]
Sounds good to me.  Should we just go with that?  We can start with just batchSize and add to it as we go along.

**Comment by wetneb** [comment]
I have built on this PR in #80 with the proposed consensus summarized by @fsteeg, so closing this one.

**Pull request closed without merging**
